#dcoker compose for express and postgres
version: '3.7'
services:
  web:
    build: .Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Ngalam#2022
      - POSTGRES_USER=Firman
      - POSTGRES_DB=db_mci
